site_name: "HCPh :: SOPs"
site_description: Templates and bootstrapping documentation for MRI standard operating procedures (SOPs)
site_author: The AxonLab

# Copyright
copyright: Copyright © 2023

nav:
    - Home: index.md
    - Change History: changes.md
    - Recruitment, Scheduling, and Screening:
      - Recruitment and screening: recruitment-scheduling-screening/recruitment.md
      - Scheduling: recruitment-scheduling-screening/scheduling.md
    - Data collection:
      - Preliminary work: data-collection/preliminary.md
      - Before each session: data-collection/pre-session.md
      - Preparing the participant: data-collection/participant-prep.md
      - Notes on the scanner's console and recording devices: data-collection/scanning-notes.md
      - Running the scanning session: data-collection/scanning.md
      - Session tear-down: data-collection/tear-down.md
      - Emergency procedures: data-collection/emergency-procedures.md
    - Data management: data-storage.md
    - Preprocessing: preprocessing.md
    - Release of data: release.md
theme:
  name: material
  features:
    - tabs
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - macros:
      include_dir: code
      include_yaml:
        - secrets: 'secrets/settings.yml'
      on_undefined: lax
  - mkpdfs:
      company: Lausanne University Hospital (CHUV)
      author: The Axon Lab
      toc_title: Table of Contents
      design: design/report.css
      output_path: pdf/documentation.pdf

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - markdown_include.include:
      base_path: docs

extra_css:
  - stylesheets/extra.css
