site_name: "HCPh :: SOPs"
site_description: Templates and bootstrapping documentation for MRI standard operating procedures (SOPs)
site_author: The AxonLab

# Copyright
copyright: Copyright &copy; 2022

nav:
    - Home: index.md
    - Change History: changes.md
    - Recruitment, Scheduling, and Screening:
      - Introduction: recruitment-scheduling-screening/index.md
      - Example 1: recruitment-scheduling-screening/example1.md
      - Example 2: recruitment-scheduling-screening/example2.md
    - Data collection:
      - Preliminary work: data-collection/preliminary.md
      - Before each session: data-collection/pre-session.md
      - Preparing the participant: data-collection/participant-prep.md
      - Running the scanning session: data-collection/scanning.md
      - Session tear-down: data-collection/tear-down.md
    - Data management: data-storage.md
    - After the session: post-session.md
    - Quality Assessment and Control: qa-qc.md
    - Preprocessing: preprocessing.md
    - Release of data: release.md
theme:
  name: material
  features:
    - tabs
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - macros:
      include_dir: code

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - markdown_include.include:
      base_path: docs

extra_css:
  - stylesheets/extra.css
