blank_issues_enabled: true
name: Scan session
description: log session
title: "[SCAN] sub-001_ses-yyy"
labels: [scan]
assignees: 
  - acionca
body:
- type: markdown
  attributes:
    value: "# general infos"

- type: checkboxes
  id: setup
  attributes:
    label: Setup
    description: Check all the equipment that was set up
    options:
      - label: Syncbox
      - label: Biopac
      - label: Gas analyzer
      - label: EyeTracker
      - label: PsychoPy
      - label: Acqknowledge
      - label: Respiration belt
      - label: ECG
      


- type: textarea
  attributes:
    label: General notes


- type: markdown
  attributes:
    value: "## Anatomical scans"
- type: checkboxes
  attributes:
    label: Anatomical scans completion
    options:
      - label: Localizer was completed.
      - label: Localizer looked ok.
      - label: T1w was completed.
      - label: T1w looked ok.
- type: dropdown
  attributes:
    label: anat issues
    multiple: true
    options:
      - noisy localizer
      - badly placed FoV
      - bad t1w quality (give more detail in the notes)
      - interrupted scan
- type: textarea
  attributes:
    label: Anatomical scans notes

- type: markdown
  attributes:
    value: "## Diffusion scan"
- type: checkboxes
  attributes:
    label: Diffusion scan completion
    options:
      - label: Diffusion was completed.
- type: dropdown
  attributes:
    label: diffusions issues
    multiple: true
    options:
      - participant fell asleep
      - excessive motion
      - interrupted scan
- type: textarea
  attributes:
    label: Diffusion scan notes
    description: If you detected an issue, please describe it in detail here.

- type: markdown
  attributes:
    value: "## Fieldmap scans"
- type: checkboxes
  attributes:
    label: Fieldmap scans completion
    options:
      - label: DWI was completed.
      - label: GRE was completed.
      - label: EPI BOLD was completed.
      - label: Physiological signals are still recording and look ok.
- type: dropdown
  attributes:
    label: fieldmaps issues
    multiple: true
    options:
      - interrupted scan
- type: textarea
  attributes:
    label: Fieldmap scans notes
    description: If you detected an issue, please describe it in detail here.


- type: markdown
  attributes:
    value: "## Functional scans"
- type: checkboxes
  attributes:
    label: Positive-control task completion
    options:
      - label: Positive-control task was completed.
      - label: Physiological signals are still recording and look ok.
- type: dropdown
  attributes:
    label: task-pct issues
    multiple: true
    options:
      - participant fell asleep
      - participant did not perform the task
      - task/physiopy/screen issue
      - excessive motion
      - eye-tracking issues (crash, pupil loss)
      - interrupted scan
- type: textarea
  attributes:
    label: Positive-control task notes
    description: If you detected an issue, please describe it in detail here.
    
- type: checkboxes
  attributes:
    label: Resting-state completion
    options:
      - label: Resting-state was completed.
      - label: Physiological signals are still recording and look ok.
- type: dropdown
  attributes:
    label: task-rest issues
    multiple: true
    options:
      - participant fell asleep
      - excessive motion
      - naturalistic movie issue
      - eye-tracking issues (crash, pupil loss)
      - interrupted scan
- type: textarea
  attributes:
    label: Resting-state notes
    description: If you detected an issue, please describe it in detail here.
    
- type: checkboxes
  attributes:
    label: Breath-holding task completion
    options:
      - label: Breath-holding task was completed.
- type: dropdown
  attributes:
    label: task-bht issues
    multiple: true
    options:
      - participant fell asleep
      - participant did not perform the task
      - task/physiopy/screen issue
      - excessive motion
      - respiration belt issue
      - interrupted scan
- type: textarea
  attributes:
    label: Breath-holding task notes
    description: If you detected an issue, please describe it in detail here.
