name: Embed code in markdown

on:
  push:
    branches:
      - mkdocs
      - fix/refine_PACs_info

jobs:
  embed-code:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout current repo"
        uses: actions/checkout@v3
      - name: "Run entrypoint script."
        uses: urmzd/embed-md@v1.0.2
        id: "embed-code"
        with:
          markdown-files: "data-storage.md"
          commit-message: "synchronizing code in data-storage.md"